spring.application.name=military-asset-management

server.port=8081

spring.datasource.url=jdbc:mysql://localhost:3306/mams?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=Rakesh143#
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

app.jwt.secret=ThisIsADevelopmentSecretKeyForMAMS2026VeryLong
app.jwt.expiration=86400000

spring.jackson.serialization.WRITE_DATES_AS_TIMESTAMPS=false